namespace simple_bloomberg_terminal.Models.Enums;

public enum GicsIndustry
{
    // ENERGY
    ENERGY_EQUIPMENT_AND_SERVICES,
    OIL_GAS_AND_CONSUMABLE_FUELS,

    // MATERIALS
    CHEMICALS,
    CONSTRUCTION_MATERIALS,
    CONTAINERS_AND_PACKAGING,
    METALS_AND_MINING,
    PAPER_AND_FOREST_PRODUCTS,

    // INDUSTRIALS
    AEROSPACE_AND_DEFENSE,
    BUILDING_PRODUCTS,
    CONSTRUCTION_AND_ENGINEERING,
    ELECTRICAL_EQUIPMENT,
    INDUSTRIAL_CONGLOMERATES,
    MACHINERY,
    TRADING_COMPANIES_AND_DISTRIBUTORS,
    COMMERCIAL_SERVICES_AND_SUPPLIES,
    PROFESSIONAL_SERVICES,
    AIR_FREIGHT_AND_LOGISTICS,
    PASSENGER_AIRLINES,
    MARINE_TRANSPORTATION,
    GROUND_TRANSPORTATION,
    TRANSPORTATION_INFRASTRUCTURE,

    // CONSUMER_DISCRETIONARY
    AUTOMOBILE_COMPONENTS,
    AUTOMOBILES,
    HOUSEHOLD_DURABLES,
    LEISURE_PRODUCTS,
    TEXTILES_APPAREL_AND_LUXURY_GOODS,
    HOTELS_RESTAURANTS_AND_LEISURE,
    DIVERSIFIED_CONSUMER_SERVICES,
    DISTRIBUTORS,
    BROADLINE_RETAIL,
    SPECIALTY_RETAIL,

    // CONSUMER_STAPLES
    CONSUMER_STAPLES_DISTRIBUTION_AND_RETAIL,
    BEVERAGES,
    FOOD_PRODUCTS,
    TOBACCO,
    HOUSEHOLD_PRODUCTS,
    PERSONAL_CARE_PRODUCTS,

    // HEALTH_CARE
    HEALTH_CARE_EQUIPMENT_AND_SUPPLIES,
    HEALTH_CARE_PROVIDERS_AND_SERVICES,
    HEALTH_CARE_TECHNOLOGY,
    BIOTECHNOLOGY,
    PHARMACEUTICALS,
    LIFE_SCIENCES_TOOLS_AND_SERVICES,

    // FINANCIALS
    BANKS,
    FINANCIAL_SERVICES,
    CONSUMER_FINANCE,
    CAPITAL_MARKETS,
    MORTGAGE_REAL_ESTATE_INVESTMENT_TRUSTS,
    INSURANCE,

    // INFORMATION_TECHNOLOGY
    IT_SERVICES,
    SOFTWARE,
    COMMUNICATIONS_EQUIPMENT,
    TECHNOLOGY_HARDWARE_STORAGE_AND_PERIPHERALS,
    ELECTRONIC_EQUIPMENT_INSTRUMENTS_AND_COMPONENTS,
    SEMICONDUCTORS_AND_SEMICONDUCTOR_EQUIPMENT,

    // COMMUNICATION_SERVICES
    DIVERSIFIED_TELECOMMUNICATION_SERVICES,
    WIRELESS_TELECOMMUNICATION_SERVICES,
    MEDIA,
    ENTERTAINMENT,
    INTERACTIVE_MEDIA_AND_SERVICES,

    // UTILITIES
    ELECTRIC_UTILITIES,
    GAS_UTILITIES,
    MULTI_UTILITIES,
    WATER_UTILITIES,
    INDEPENDENT_POWER_AND_RENEWABLE_ELECTRICITY_PRODUCERS,

    // REAL_ESTATE
    DIVERSIFIED_REITS,
    INDUSTRIAL_REITS,
    HOTEL_AND_RESORT_REITS,
    OFFICE_REITS,
    HEALTH_CARE_REITS,
    RESIDENTIAL_REITS,
    RETAIL_REITS,
    SPECIALIZED_REITS,
    REAL_ESTATE_MANAGEMENT_AND_DEVELOPMENT
}

public static class GicsIndustryExtensions
{
    private static readonly Dictionary<GicsIndustry, Sector> SectorMap = new()
    {
        { GicsIndustry.ENERGY_EQUIPMENT_AND_SERVICES, Sector.ENERGY },
        { GicsIndustry.OIL_GAS_AND_CONSUMABLE_FUELS, Sector.ENERGY },

        { GicsIndustry.CHEMICALS, Sector.MATERIALS },
        { GicsIndustry.CONSTRUCTION_MATERIALS, Sector.MATERIALS },
        { GicsIndustry.CONTAINERS_AND_PACKAGING, Sector.MATERIALS },
        { GicsIndustry.METALS_AND_MINING, Sector.MATERIALS },
        { GicsIndustry.PAPER_AND_FOREST_PRODUCTS, Sector.MATERIALS },

        { GicsIndustry.AEROSPACE_AND_DEFENSE, Sector.INDUSTRIALS },
        { GicsIndustry.BUILDING_PRODUCTS, Sector.INDUSTRIALS },
        { GicsIndustry.CONSTRUCTION_AND_ENGINEERING, Sector.INDUSTRIALS },
        { GicsIndustry.ELECTRICAL_EQUIPMENT, Sector.INDUSTRIALS },
        { GicsIndustry.INDUSTRIAL_CONGLOMERATES, Sector.INDUSTRIALS },
        { GicsIndustry.MACHINERY, Sector.INDUSTRIALS },
        { GicsIndustry.TRADING_COMPANIES_AND_DISTRIBUTORS, Sector.INDUSTRIALS },
        { GicsIndustry.COMMERCIAL_SERVICES_AND_SUPPLIES, Sector.INDUSTRIALS },
        { GicsIndustry.PROFESSIONAL_SERVICES, Sector.INDUSTRIALS },
        { GicsIndustry.AIR_FREIGHT_AND_LOGISTICS, Sector.INDUSTRIALS },
        { GicsIndustry.PASSENGER_AIRLINES, Sector.INDUSTRIALS },
        { GicsIndustry.MARINE_TRANSPORTATION, Sector.INDUSTRIALS },
        { GicsIndustry.GROUND_TRANSPORTATION, Sector.INDUSTRIALS },
        { GicsIndustry.TRANSPORTATION_INFRASTRUCTURE, Sector.INDUSTRIALS },

        { GicsIndustry.AUTOMOBILE_COMPONENTS, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.AUTOMOBILES, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.HOUSEHOLD_DURABLES, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.LEISURE_PRODUCTS, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.TEXTILES_APPAREL_AND_LUXURY_GOODS, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.HOTELS_RESTAURANTS_AND_LEISURE, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.DIVERSIFIED_CONSUMER_SERVICES, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.DISTRIBUTORS, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.BROADLINE_RETAIL, Sector.CONSUMER_DISCRETIONARY },
        { GicsIndustry.SPECIALTY_RETAIL, Sector.CONSUMER_DISCRETIONARY },

        { GicsIndustry.CONSUMER_STAPLES_DISTRIBUTION_AND_RETAIL, Sector.CONSUMER_STAPLES },
        { GicsIndustry.BEVERAGES, Sector.CONSUMER_STAPLES },
        { GicsIndustry.FOOD_PRODUCTS, Sector.CONSUMER_STAPLES },
        { GicsIndustry.TOBACCO, Sector.CONSUMER_STAPLES },
        { GicsIndustry.HOUSEHOLD_PRODUCTS, Sector.CONSUMER_STAPLES },
        { GicsIndustry.PERSONAL_CARE_PRODUCTS, Sector.CONSUMER_STAPLES },

        { GicsIndustry.HEALTH_CARE_EQUIPMENT_AND_SUPPLIES, Sector.HEALTH_CARE },
        { GicsIndustry.HEALTH_CARE_PROVIDERS_AND_SERVICES, Sector.HEALTH_CARE },
        { GicsIndustry.HEALTH_CARE_TECHNOLOGY, Sector.HEALTH_CARE },
        { GicsIndustry.BIOTECHNOLOGY, Sector.HEALTH_CARE },
        { GicsIndustry.PHARMACEUTICALS, Sector.HEALTH_CARE },
        { GicsIndustry.LIFE_SCIENCES_TOOLS_AND_SERVICES, Sector.HEALTH_CARE },

        { GicsIndustry.BANKS, Sector.FINANCIALS },
        { GicsIndustry.FINANCIAL_SERVICES, Sector.FINANCIALS },
        { GicsIndustry.CONSUMER_FINANCE, Sector.FINANCIALS },
        { GicsIndustry.CAPITAL_MARKETS, Sector.FINANCIALS },
        { GicsIndustry.MORTGAGE_REAL_ESTATE_INVESTMENT_TRUSTS, Sector.FINANCIALS },
        { GicsIndustry.INSURANCE, Sector.FINANCIALS },

        { GicsIndustry.IT_SERVICES, Sector.INFORMATION_TECHNOLOGY },
        { GicsIndustry.SOFTWARE, Sector.INFORMATION_TECHNOLOGY },
        { GicsIndustry.COMMUNICATIONS_EQUIPMENT, Sector.INFORMATION_TECHNOLOGY },
        { GicsIndustry.TECHNOLOGY_HARDWARE_STORAGE_AND_PERIPHERALS, Sector.INFORMATION_TECHNOLOGY },
        { GicsIndustry.ELECTRONIC_EQUIPMENT_INSTRUMENTS_AND_COMPONENTS, Sector.INFORMATION_TECHNOLOGY },
        { GicsIndustry.SEMICONDUCTORS_AND_SEMICONDUCTOR_EQUIPMENT, Sector.INFORMATION_TECHNOLOGY },

        { GicsIndustry.DIVERSIFIED_TELECOMMUNICATION_SERVICES, Sector.COMMUNICATION_SERVICES },
        { GicsIndustry.WIRELESS_TELECOMMUNICATION_SERVICES, Sector.COMMUNICATION_SERVICES },
        { GicsIndustry.MEDIA, Sector.COMMUNICATION_SERVICES },
        { GicsIndustry.ENTERTAINMENT, Sector.COMMUNICATION_SERVICES },
        { GicsIndustry.INTERACTIVE_MEDIA_AND_SERVICES, Sector.COMMUNICATION_SERVICES },

        { GicsIndustry.ELECTRIC_UTILITIES, Sector.UTILITIES },
        { GicsIndustry.GAS_UTILITIES, Sector.UTILITIES },
        { GicsIndustry.MULTI_UTILITIES, Sector.UTILITIES },
        { GicsIndustry.WATER_UTILITIES, Sector.UTILITIES },
        { GicsIndustry.INDEPENDENT_POWER_AND_RENEWABLE_ELECTRICITY_PRODUCERS, Sector.UTILITIES },

        { GicsIndustry.DIVERSIFIED_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.INDUSTRIAL_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.HOTEL_AND_RESORT_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.OFFICE_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.HEALTH_CARE_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.RESIDENTIAL_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.RETAIL_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.SPECIALIZED_REITS, Sector.REAL_ESTATE },
        { GicsIndustry.REAL_ESTATE_MANAGEMENT_AND_DEVELOPMENT, Sector.REAL_ESTATE },
    };

    public static Sector GetSector(this GicsIndustry industry) => SectorMap[industry];
}
