// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simple_bloomberg_terminal.Data;

#nullable disable

namespace simple_bloomberg_terminal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanyEvent", b =>
                {
                    b.Property<long>("CompaniesId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.HasKey("CompaniesId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("CompanyEvent");
                });

            modelBuilder.Entity("CountryEvent", b =>
                {
                    b.Property<long>("CountriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.HasKey("CountriesId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("CountryEvent");
                });

            modelBuilder.Entity("CountryTradeBloc", b =>
                {
                    b.Property<long>("CountriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeBlocsId")
                        .HasColumnType("bigint");

                    b.HasKey("CountriesId", "TradeBlocsId");

                    b.HasIndex("TradeBlocsId");

                    b.ToTable("CountryTradeBloc");
                });

            modelBuilder.Entity("EventTradeBloc", b =>
                {
                    b.Property<long>("EventsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeBlocsId")
                        .HasColumnType("bigint");

                    b.HasKey("EventsId", "TradeBlocsId");

                    b.HasIndex("TradeBlocsId");

                    b.ToTable("EventTradeBloc");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ProfilePictureData")
                        .HasColumnType("longblob");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AsOf")
                        .HasColumnType("date");

                    b.Property<string>("Cik")
                        .HasColumnType("longtext");

                    b.Property<bool>("ClassificationLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClassifyStatus")
                        .HasColumnType("int");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FmpIndustry")
                        .HasColumnType("longtext");

                    b.Property<int?>("GicsSubIndustry")
                        .HasColumnType("int");

                    b.Property<double?>("GrossMargin")
                        .HasColumnType("double");

                    b.Property<int?>("Industry")
                        .HasColumnType("int");

                    b.Property<double?>("MarketCap")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<double?>("RevenueTotal")
                        .HasColumnType("double");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyFinancial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<double?>("CostOfRevenue")
                        .HasColumnType("double");

                    b.Property<double?>("CurrentRatio")
                        .HasColumnType("double");

                    b.Property<double?>("DebtToEquity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Ebitda")
                        .HasColumnType("double");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<double?>("Eps")
                        .HasColumnType("double");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<double?>("FreeCashFlow")
                        .HasColumnType("double");

                    b.Property<double?>("GrossMargin")
                        .HasColumnType("double");

                    b.Property<double?>("GrossProfit")
                        .HasColumnType("double");

                    b.Property<double?>("NetIncome")
                        .HasColumnType("double");

                    b.Property<double?>("NetMargin")
                        .HasColumnType("double");

                    b.Property<double?>("OperatingCashFlow")
                        .HasColumnType("double");

                    b.Property<double?>("OperatingIncome")
                        .HasColumnType("double");

                    b.Property<double?>("OperatingMargin")
                        .HasColumnType("double");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("ReportedCurrency")
                        .HasColumnType("longtext");

                    b.Property<double?>("Revenue")
                        .HasColumnType("double");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<double?>("TotalCash")
                        .HasColumnType("double");

                    b.Property<double?>("TotalDebt")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "FiscalYear", "Period")
                        .IsUnique();

                    b.ToTable("CompanyFinancials");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyRisk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContributedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Evidence")
                        .HasColumnType("longtext");

                    b.Property<long?>("FilingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("SupersedesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributedByUserId");

                    b.HasIndex("FilingId");

                    b.ToTable("CompanyRisks");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyVolumeHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "WeekStart")
                        .IsUnique();

                    b.ToTable("CompanyVolumeHistories");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CostSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContributedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Evidence")
                        .HasColumnType("longtext");

                    b.Property<long?>("FilingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<long?>("RelatedCompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("SupersedesId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributedByUserId");

                    b.HasIndex("FilingId");

                    b.HasIndex("RelatedCompanyId");

                    b.ToTable("CostSources");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("GdpUsd")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("RiskRating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryAdvantage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryAdvantages");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryChallenges");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MarketPosition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CountryId");

                    b.ToTable("CountryDetails");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ImpactScore")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Filing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Form")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryDocUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.ToTable("Filings");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.FmpIndustryMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int>("SubIndustry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("FmpIndustryMappings");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.GdpSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryDetailsCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GdpUsd")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsCountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("GdpSnapshots");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.IndexConstituent", b =>
                {
                    b.Property<long>("StockIndexId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<double?>("WeightPct")
                        .HasColumnType("double");

                    b.HasKey("StockIndexId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("IndexConstituents");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.IndexImportJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContinuedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<string>("EtfTicker")
                        .HasColumnType("longtext");

                    b.Property<long?>("IndexId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Matched")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Provisioned")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<string>("StartedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalConstituents")
                        .HasColumnType("int");

                    b.Property<string>("WikiPage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IndexImportJobs");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.RevenueSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContributedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Evidence")
                        .HasColumnType("longtext");

                    b.Property<long?>("FilingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<long?>("RelatedCompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("SupersedesId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributedByUserId");

                    b.HasIndex("FilingId");

                    b.HasIndex("RelatedCompanyId");

                    b.ToTable("RevenueSources");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Scenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.ScenarioShock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Factor")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<double>("Magnitude")
                        .HasColumnType("double");

                    b.Property<long>("ScenarioId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioShocks");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.StockIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AsOf")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EtfProxy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.Property<double?>("TotalMarketCap")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("StockIndices");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.TradeBloc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TradeBlocs");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.UserApiKey", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnthropicKey")
                        .HasColumnType("longtext");

                    b.Property<string>("DeepSeekKey")
                        .HasColumnType("longtext");

                    b.Property<string>("FmpKey")
                        .HasColumnType("longtext");

                    b.Property<string>("KimiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("OpenAiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsingModel")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsingProvider")
                        .HasColumnType("longtext");

                    b.Property<string>("PerplexityKey")
                        .HasColumnType("longtext");

                    b.Property<string>("WebSearchModel")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("UserApiKeys");
                });

            modelBuilder.Entity("CompanyEvent", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryEvent", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryTradeBloc", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.TradeBloc", null)
                        .WithMany()
                        .HasForeignKey("TradeBlocsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTradeBloc", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.TradeBloc", null)
                        .WithMany()
                        .HasForeignKey("TradeBlocsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyFinancial", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("Financials")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyRisk", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("CompanyRisks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", "ContributedBy")
                        .WithMany()
                        .HasForeignKey("ContributedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Filing", "Filing")
                        .WithMany()
                        .HasForeignKey("FilingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ContributedBy");

                    b.Navigation("Filing");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CompanyVolumeHistory", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("VolumeHistory")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CostSource", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("CostSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", "ContributedBy")
                        .WithMany()
                        .HasForeignKey("ContributedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Filing", "Filing")
                        .WithMany()
                        .HasForeignKey("FilingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "RelatedCompany")
                        .WithMany("CostFromDependents")
                        .HasForeignKey("RelatedCompanyId");

                    b.Navigation("Company");

                    b.Navigation("ContributedBy");

                    b.Navigation("Filing");

                    b.Navigation("RelatedCompany");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryAdvantage", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("Advantages")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Advantages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryChallenge", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("Challenges")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("Challenges")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithOne("Details")
                        .HasForeignKey("simple_bloomberg_terminal.Models.Entities.CountryDetails", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Filing", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.GdpSnapshot", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.CountryDetails", null)
                        .WithMany("GdpHistory")
                        .HasForeignKey("CountryDetailsCountryId");

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Country", "Country")
                        .WithMany("GdpHistory")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.IndexConstituent", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.StockIndex", "StockIndex")
                        .WithMany("Constituents")
                        .HasForeignKey("StockIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("StockIndex");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.RevenueSource", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "Company")
                        .WithMany("RevenueSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", "ContributedBy")
                        .WithMany()
                        .HasForeignKey("ContributedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Filing", "Filing")
                        .WithMany()
                        .HasForeignKey("FilingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Company", "RelatedCompany")
                        .WithMany("RevenueFromDependents")
                        .HasForeignKey("RelatedCompanyId");

                    b.Navigation("Company");

                    b.Navigation("ContributedBy");

                    b.Navigation("Filing");

                    b.Navigation("RelatedCompany");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.ScenarioShock", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.Scenario", "Scenario")
                        .WithMany("Shocks")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.UserApiKey", b =>
                {
                    b.HasOne("simple_bloomberg_terminal.Models.Entities.AppUser", null)
                        .WithOne()
                        .HasForeignKey("simple_bloomberg_terminal.Models.Entities.UserApiKey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Company", b =>
                {
                    b.Navigation("CompanyRisks");

                    b.Navigation("CostFromDependents");

                    b.Navigation("CostSources");

                    b.Navigation("Financials");

                    b.Navigation("RevenueFromDependents");

                    b.Navigation("RevenueSources");

                    b.Navigation("VolumeHistory");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Country", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Challenges");

                    b.Navigation("Companies");

                    b.Navigation("Details");

                    b.Navigation("GdpHistory");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.CountryDetails", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Challenges");

                    b.Navigation("GdpHistory");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.Scenario", b =>
                {
                    b.Navigation("Shocks");
                });

            modelBuilder.Entity("simple_bloomberg_terminal.Models.Entities.StockIndex", b =>
                {
                    b.Navigation("Constituents");
                });
#pragma warning restore 612, 618
        }
    }
}
